# Generated by Django 4.2.4 on 2023-08-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folioApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=500)),
                ("link", models.TextField()),
                ("image", models.URLField()),
            ],
        ),
    ]
