# Generated by Django 4.2.4 on 2023-08-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folioApp", "0004_skill_delete_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subject", models.TextField(max_length=500)),
                ("date", models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=500)),
                ("logo", models.TextField()),
            ],
        ),
    ]
