# Generated by Django 4.2.4 on 2023-08-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folioApp", "0005_education_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="files/projects"),
        ),
    ]
